---
ID: "32b53f54-34e0-4392-8dd0-88fcdd073972"
Parent: "f84f4dde-30d1-4ce5-b51c-c58d0ad1fa12"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home v2/gulp/tasks/sprites
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/32B53F5434E043928DD088FCDD073972.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "295e4ecf-1079-46ec-8e25-d577c6bbfea4"
  Value: aW1wb3J0IGd1bHAgZnJvbSAiZ3VscCI7DQppbXBvcnQgc3ByaXRlc21pdGggZnJvbSAnZ3VscC5zcHJpdGVzbWl0aCc7DQppbXBvcnQgY29uZmlnIGZyb20gJy4uL2NvbmZpZyc7DQoNCmd1bHAudGFzaygnc3ByaXRlLWZsYWcnLCBmdW5jdGlvbigpIHsNCiAgICBsZXQgY29uZiA9IGNvbmZpZy5zcHJpdGVzLmZsYWdzLA0KICAgICAgICBzcHJpdGVEYXRhID0gZ3VscC5zcmMoY29uZi5mbGFnc0ZvbGRlcikucGlwZShzcHJpdGVzbWl0aChjb25mLnNwcml0ZXNtaXRoKSk7DQogICAgc3ByaXRlRGF0YS5pbWcucGlwZShndWxwLmRlc3QoY29uZi5pbWdEZXN0KSk7DQogICAgcmV0dXJuIHNwcml0ZURhdGEuY3NzLnBpcGUoZ3VscC5kZXN0KGNvbmYuY3NzRGVzdCkpOw0KfSk7
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 381
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T042721Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
