---
ID: "c582b885-e1de-4cca-b5e3-45ebcfdc13ec"
Parent: "79ccff27-fd0e-4a22-aa11-ea806bd8f7e3"
Template: "79ccff27-fd0e-4a22-aa11-ea806bd8f7e3"
Path: /sitecore/templates/Feature/Brands/Datasource/Overview/__Standard Values
DB: master
SharedFields:
- ID: "29fb049f-842b-46f3-8f0f-faa4fb7d7db0"
  Hint: Page Size
  Value: 12
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190705T061951Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
