---
ID: "43132241-f93d-42dd-914d-2a186a2a2804"
Parent: "da88f036-b002-48d3-b1b1-d4e1c1843261"
Template: "e24e0789-a058-48bf-abb6-c69c0e60b6b7"
Path: /sitecore/content/Habitat Sites/Habitat Home Basic/Presentation/Partial Designs/Footer/Data/Navigation Links/Computers Column/Productivity
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180320T211244Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "dd05144a-bd66-4ea3-956a-4b7104daaba3"
      Hint: Link
      Value: |
        <link id="{927d008c-1b6d-46f0-8535-4175ddb7c716}" querystring="" text="Productivity" anchor="" url="/Habitat Sites/Habitat Home Basic/home/computers" title="" class="" linktype="internal" />
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180324T014617Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
