---
ID: "51909104-7b6c-49d6-9654-99622e9c0e9e"
Parent: "a7f39d7d-406c-4203-b68e-5f967964dba8"
Template: "7e33cfbd-1060-4a7c-97b5-fd3785bd5085"
Path: /sitecore/content/Habitat Home Corporate/Settings/Form Actions Settings/Contact Identification/Default
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180201T053213Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 標準
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181024T125802Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
