---
ID: "85b5a992-703a-47c2-9b38-52c6a52855fc"
Parent: "f4e54f06-fe90-4d8a-ade7-cabc76036530"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Habitat Sites/Habitat Home/Weekly Fitness Report Signup/Page/Section/CyclingTypeSection/Checkbox List/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181206T044833Z
