---
ID: "9dafc921-c83d-4a95-977f-39efa0b5d586"
Parent: "1796734c-6fe5-459b-a51d-def28308967b"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home Basic/sass/base
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T063530Z
