---
ID: "e48eded4-b2d7-4e13-a7df-703844e4c2fb"
Parent: "ea4dfbfb-3ad8-4e45-8f57-271dd2816262"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home v2/sass/base
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T042952Z
